services:
  - type: web
    name: interntrack
    env: python
    region: oregon
    plan: free
    runtime: python-3.11
    buildCommand: cd "final project" && python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: sh ./start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
