services:
  - type: web
    name: interntrack
    env: python
    region: oregon
    plan: free
    runtime: python-3.11
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: bash -lc 'python -m pip install --upgrade pip && python -m pip install gunicorn==20.1.0 && python -m gunicorn web_app:app --bind 0.0.0.0:$PORT'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
